-- Add B1 (Light Motor Vehicles) Mock Test Questions
-- Comprehensive questions covering road signs, rules, safety, and vehicle operation

-- Road Signs and Markings (10 questions)
INSERT INTO questions (id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, category, license_category, difficulty, created_at) VALUES
('q-b1-001', 'What does a red octagonal sign mean?', 'Give way', 'Stop', 'No entry', 'Speed limit', 'B', 'A red octagonal (8-sided) sign is universally recognized as a STOP sign. You must come to a complete stop.', 'ROAD_SIGNS', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-002', 'What does a triangular sign with a red border mean?', 'Information', 'Warning', 'Prohibition', 'Mandatory instruction', 'B', 'Triangular signs with red borders are warning signs that alert drivers to potential hazards ahead.', 'ROAD_SIGNS', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-003', 'What does a circular sign with a red border and diagonal line mean?', 'Warning', 'Prohibition', 'End of restriction', 'Mandatory action', 'B', 'A red circle with a diagonal line indicates prohibition - something is not allowed.', 'ROAD_SIGNS', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-004', 'What does a blue circular sign indicate?', 'Warning', 'Prohibition', 'Mandatory instruction', 'Information', 'C', 'Blue circular signs give mandatory instructions that must be followed.', 'ROAD_SIGNS', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-005', 'What does a broken white line on the road mean?', 'No overtaking', 'You may cross if safe', 'Stop line', 'Parking area', 'B', 'A broken white line separates lanes and you may cross it to overtake if it is safe to do so.', 'ROAD_SIGNS', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-006', 'What does a continuous yellow line at the edge of the road mean?', 'No stopping', 'No parking', 'Bus lane', 'Cycle lane', 'B', 'A continuous yellow line at the road edge means no parking is allowed at any time.', 'ROAD_SIGNS', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-007', 'What does a rectangular blue sign with white symbols indicate?', 'Warning', 'Prohibition', 'Information', 'Mandatory instruction', 'C', 'Rectangular blue signs provide information to drivers about facilities, directions, or road conditions.', 'ROAD_SIGNS', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-008', 'What should you do when you see a yellow traffic light?', 'Speed up to cross', 'Stop if safe to do so', 'Continue at same speed', 'Sound your horn', 'B', 'A yellow light means stop if you can do so safely. It warns that the light is about to turn red.', 'ROAD_SIGNS', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-009', 'What does a white "X" on the road mean?', 'Pedestrian crossing ahead', 'No stopping zone', 'Railway crossing ahead', 'Speed bump ahead', 'C', 'A white X painted on the road warns of a railway crossing ahead.', 'ROAD_SIGNS', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-010', 'What does a sign showing two cars side by side mean?', 'Overtaking allowed', 'No overtaking', 'Two-way traffic', 'Dual carriageway', 'B', 'This sign prohibits overtaking in that section of road.', 'ROAD_SIGNS', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000);

-- Traffic Rules and Right of Way (10 questions)
INSERT INTO questions (id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, category, license_category, difficulty, created_at) VALUES
('q-b1-011', 'At a roundabout, who has the right of way?', 'Vehicles entering', 'Vehicles already in the roundabout', 'Larger vehicles', 'Vehicles from the right', 'B', 'Vehicles already in the roundabout have right of way. You must give way before entering.', 'TRAFFIC_RULES', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-012', 'When two vehicles arrive at an uncontrolled intersection at the same time, who has right of way?', 'The faster vehicle', 'The vehicle on the right', 'The larger vehicle', 'The vehicle going straight', 'B', 'At uncontrolled intersections, give way to vehicles approaching from your right.', 'TRAFFIC_RULES', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-013', 'What is the maximum speed limit in a built-up area unless otherwise indicated?', '30 km/h', '50 km/h', '60 km/h', '80 km/h', 'B', 'The default speed limit in built-up areas (towns and cities) is 50 km/h unless signs indicate otherwise.', 'TRAFFIC_RULES', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-014', 'When must you use your headlights?', 'Only at night', 'During rain or poor visibility', 'Between sunset and sunrise, and in poor visibility', 'Only when required by police', 'C', 'Headlights must be used between sunset and sunrise, and whenever visibility is poor due to weather conditions.', 'TRAFFIC_RULES', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-015', 'What is the minimum safe following distance in good conditions?', '1 second', '2 seconds', '3 seconds', '5 seconds', 'B', 'Maintain at least a 2-second following distance in good conditions. Increase this in poor conditions.', 'TRAFFIC_RULES', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-016', 'When are you allowed to use your horn in a built-up area?', 'Anytime', 'Only in emergencies', 'Between 6am and 10pm', 'Never', 'B', 'In built-up areas, use your horn only to warn of danger or in emergencies, not to express frustration.', 'TRAFFIC_RULES', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-017', 'What should you do when an emergency vehicle with sirens approaches?', 'Speed up', 'Stop immediately', 'Pull over safely and give way', 'Continue at same speed', 'C', 'When emergency vehicles approach with sirens, safely pull over to the side and give way.', 'TRAFFIC_RULES', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-018', 'When is it illegal to use a mobile phone while driving?', 'Never, it is always allowed', 'Only when texting', 'When held in hand', 'Only on highways', 'C', 'It is illegal to hold and use a mobile phone while driving. Use hands-free devices only.', 'TRAFFIC_RULES', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-019', 'What is the legal blood alcohol limit for drivers in Kenya?', '0.00%', '0.05%', '0.08%', '0.10%', 'A', 'Kenya has a zero-tolerance policy. The legal blood alcohol limit is 0.00% - no alcohol while driving.', 'TRAFFIC_RULES', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-020', 'How far from a pedestrian crossing must you not park?', '5 meters', '10 meters', '15 meters', '20 meters', 'C', 'You must not park within 15 meters of a pedestrian crossing to ensure visibility.', 'TRAFFIC_RULES', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000);

-- Vehicle Safety and Maintenance (8 questions)
INSERT INTO questions (id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, category, license_category, difficulty, created_at) VALUES
('q-b1-021', 'What is the minimum legal tread depth for car tires?', '1.0 mm', '1.6 mm', '2.0 mm', '3.0 mm', 'B', 'The minimum legal tread depth is 1.6mm across the central three-quarters of the tire.', 'VEHICLE_SAFETY', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-022', 'How often should you check your tire pressure?', 'Once a year', 'Every 6 months', 'Monthly', 'Weekly', 'D', 'Check tire pressure weekly and before long journeys for optimal safety and fuel efficiency.', 'VEHICLE_SAFETY', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-023', 'What does the oil warning light indicate?', 'Time for oil change', 'Low oil pressure', 'Oil filter blocked', 'High oil temperature', 'B', 'The oil warning light indicates low oil pressure. Stop immediately and check oil level.', 'VEHICLE_SAFETY', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-024', 'What should you do if your brakes fail while driving?', 'Turn off engine', 'Pump the brake pedal and use handbrake gradually', 'Shift to neutral', 'Swerve to avoid obstacles', 'B', 'If brakes fail, pump the pedal rapidly, downshift, and gradually apply the handbrake while steering to safety.', 'VEHICLE_SAFETY', 'B1', 'HARD', strftime('%s', 'now') * 1000),
('q-b1-025', 'What is the purpose of ABS (Anti-lock Braking System)?', 'Increase braking power', 'Prevent wheels from locking during hard braking', 'Reduce brake wear', 'Improve fuel efficiency', 'B', 'ABS prevents wheels from locking during emergency braking, maintaining steering control.', 'VEHICLE_SAFETY', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-026', 'When should you use hazard lights?', 'When parking illegally', 'When your vehicle is a temporary obstruction', 'When driving in rain', 'When overtaking', 'B', 'Use hazard lights when your vehicle is temporarily obstructing traffic or in an emergency situation.', 'VEHICLE_SAFETY', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-027', 'What does it mean if your steering wheel vibrates at high speed?', 'Normal operation', 'Wheels need balancing', 'Low fuel', 'Engine problem', 'B', 'Steering wheel vibration at high speed usually indicates wheels need balancing or alignment.', 'VEHICLE_SAFETY', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-028', 'What should you check before starting a long journey?', 'Only fuel level', 'Fuel, oil, water, and tire pressure', 'Only tire pressure', 'Only oil level', 'B', 'Before long journeys, check fuel, engine oil, coolant, tire pressure, and lights.', 'VEHICLE_SAFETY', 'B1', 'EASY', strftime('%s', 'now') * 1000);

-- Defensive Driving and Hazard Awareness (8 questions)
INSERT INTO questions (id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, category, license_category, difficulty, created_at) VALUES
('q-b1-029', 'What should you do when driving in heavy rain?', 'Increase speed to get through quickly', 'Reduce speed and increase following distance', 'Use hazard lights', 'Drive in the middle lane', 'B', 'In heavy rain, reduce speed, increase following distance, and use headlights for visibility.', 'DEFENSIVE_DRIVING', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-030', 'What is "hydroplaning"?', 'Driving on ice', 'Tires losing contact with road due to water', 'Engine overheating', 'Brake failure', 'B', 'Hydroplaning occurs when tires lose contact with the road surface due to water, causing loss of control.', 'DEFENSIVE_DRIVING', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-031', 'When should you use your mirrors?', 'Only when reversing', 'Before signaling, changing lanes, or turning', 'Only on highways', 'Once every minute', 'B', 'Check mirrors regularly, especially before signaling, changing lanes, turning, or slowing down.', 'DEFENSIVE_DRIVING', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-032', 'What is a "blind spot"?', 'Area behind the vehicle', 'Area not visible in mirrors', 'Area in front at night', 'Area under the vehicle', 'B', 'A blind spot is an area around your vehicle not visible in mirrors. Always check by turning your head.', 'DEFENSIVE_DRIVING', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-033', 'What should you do if you feel tired while driving?', 'Open windows', 'Drink coffee and continue', 'Stop and rest', 'Drive faster to reach destination', 'C', 'If tired, stop in a safe place and rest. Fatigue significantly impairs driving ability.', 'DEFENSIVE_DRIVING', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-034', 'When driving at night, when should you dip your headlights?', 'Never', 'When following another vehicle or meeting oncoming traffic', 'Only in built-up areas', 'Only on highways', 'B', 'Dip headlights when following another vehicle or when meeting oncoming traffic to avoid dazzling other drivers.', 'DEFENSIVE_DRIVING', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-035', 'What is the safest way to drive through a flooded road?', 'Drive fast to avoid stalling', 'Drive slowly in low gear', 'Avoid flooded roads', 'Follow other vehicles closely', 'C', 'Avoid flooded roads when possible. If unavoidable, drive slowly in low gear, but never risk deep water.', 'DEFENSIVE_DRIVING', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-036', 'What should you do when approaching a school zone?', 'Maintain normal speed', 'Reduce speed and watch for children', 'Sound horn to warn children', 'Speed up to pass quickly', 'B', 'Reduce speed in school zones and be extra vigilant for children who may cross unexpectedly.', 'DEFENSIVE_DRIVING', 'B1', 'EASY', strftime('%s', 'now') * 1000);

-- Parking and Maneuvering (6 questions)
INSERT INTO questions (id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, category, license_category, difficulty, created_at) VALUES
('q-b1-037', 'When parallel parking, how far from the curb should your vehicle be?', '10 cm', '30 cm', '50 cm', '1 meter', 'B', 'When parallel parking, your vehicle should be within 30cm of the curb.', 'PARKING', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-038', 'When parking on a hill facing upward, which way should you turn your wheels?', 'Away from curb', 'Toward the curb', 'Straight', 'Either direction', 'B', 'When parking uphill, turn wheels away from curb so the vehicle rolls back into the curb if brakes fail.', 'PARKING', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-039', 'When parking on a hill facing downward, which way should you turn your wheels?', 'Away from curb', 'Toward the curb', 'Straight', 'Either direction', 'B', 'When parking downhill, turn wheels toward the curb so the vehicle rolls into the curb if brakes fail.', 'PARKING', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-040', 'What should you do before reversing?', 'Sound horn', 'Check all around and use mirrors', 'Turn on hazard lights', 'Reverse quickly', 'B', 'Before reversing, check all around including blind spots, use mirrors, and reverse slowly.', 'PARKING', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-041', 'Where is it illegal to park?', 'Near a street light', 'Within 6 meters of a junction', 'On a wide road', 'In a parking bay', 'B', 'It is illegal to park within 6 meters of a road junction as it obstructs visibility.', 'PARKING', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-042', 'What is the three-point turn used for?', 'Parking', 'Turning around in a narrow road', 'Emergency stops', 'Overtaking', 'B', 'A three-point turn is used to turn your vehicle around in a narrow road where a U-turn is not possible.', 'PARKING', 'B1', 'EASY', strftime('%s', 'now') * 1000);

-- Environmental and Fuel Efficiency (4 questions)
INSERT INTO questions (id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, category, license_category, difficulty, created_at) VALUES
('q-b1-043', 'What driving technique improves fuel efficiency?', 'Rapid acceleration', 'Smooth acceleration and anticipating traffic', 'High speed driving', 'Frequent braking', 'B', 'Smooth acceleration, maintaining steady speed, and anticipating traffic flow improves fuel efficiency.', 'ECO_DRIVING', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-044', 'How does under-inflated tires affect your vehicle?', 'Improves comfort', 'Increases fuel consumption', 'Improves handling', 'No effect', 'B', 'Under-inflated tires increase rolling resistance, leading to higher fuel consumption and tire wear.', 'ECO_DRIVING', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000),
('q-b1-045', 'What should you do to reduce emissions when stationary for a long time?', 'Rev the engine', 'Turn off the engine', 'Keep engine running', 'Use air conditioning', 'B', 'Turn off the engine when stationary for more than a minute to reduce emissions and save fuel.', 'ECO_DRIVING', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-046', 'Which gear should you use when driving downhill?', 'Neutral', 'High gear', 'Low gear', 'Any gear', 'C', 'Use a low gear when driving downhill to use engine braking and reduce wear on brakes.', 'ECO_DRIVING', 'B1', 'MEDIUM', strftime('%s', 'now') * 1000);

-- Pedestrians and Vulnerable Road Users (4 questions)
INSERT INTO questions (id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, category, license_category, difficulty, created_at) VALUES
('q-b1-047', 'Who has priority at a zebra crossing?', 'Vehicles', 'Pedestrians', 'Larger vehicles', 'Whoever arrives first', 'B', 'Pedestrians always have priority at zebra crossings. You must stop and give way.', 'PEDESTRIANS', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-048', 'What extra care should you take when passing cyclists?', 'Sound horn continuously', 'Give at least 1 meter clearance', 'Pass as quickly as possible', 'Flash headlights', 'B', 'Give cyclists at least 1 meter clearance when passing and watch for sudden movements.', 'PEDESTRIANS', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-049', 'What should you do when you see a school bus stopped with lights flashing?', 'Overtake quickly', 'Stop and wait until it is safe', 'Sound horn', 'Continue at same speed', 'B', 'Stop and wait when a school bus has stopped with lights flashing as children may be crossing.', 'PEDESTRIANS', 'B1', 'EASY', strftime('%s', 'now') * 1000),
('q-b1-050', 'When should you be extra cautious of motorcyclists?', 'Only at night', 'At junctions and when changing lanes', 'Only in rain', 'Never', 'B', 'Be extra cautious of motorcyclists at junctions and when changing lanes as they are less visible.', 'PEDESTRIANS', 'B1', 'EASY', strftime('%s', 'now') * 1000);
